/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 food_truck.gltf 
Author: bronwenalexina (https://sketchfab.com/bronwenalexina)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-food-truck-bf66906506eb48a2a7f88ab90c7be8b0
Title: Cute Food truck
*/

import React from "react";
import { Center, useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/food_truck.gltf");
  return (
    <Center>
      <group {...props} dispose={null}>
        <mesh
          geometry={nodes.Cube008_Material001_0.geometry}
          material={materials["Material.001"]}
          position={[0, 0, 0]} // reset position to center it
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.4} // scale down to 50%
        />
      </group>
    </Center>
  );
}

useGLTF.preload("/food_truck.gltf");
